# Model arguments
model_name_or_path: allenai/scitulu-7b
model_revision: main
tokenizer_name_or_path: allenai/scitulu-7b
torch_dtype: bfloat16
attn_implementation: flash_attention_2

################ ASPECT #################
aspect: all

# Data training arguments
dataset_mixer:
  boda/review_evaluation_automatic_labels: 1.0
dataset_splits:
- train
- test
dataset_configs:
- all
preprocessing_num_workers: 12

# LoRA arguments
load_in_4bit: false
use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# SFT trainer config
bf16: true
dataset_kwargs:
  add_special_tokens: false  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: false # No need to add <eos> across samples
do_eval: true
eval_strategy: epoch
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: boda/review_evaluation_all
hub_strategy: every_save
learning_rate: 2.0e-04
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 3
output_dir: review_evaluation_checkpoints
# output_dir: /l/users/abdelrahman.sadallah/review_evaluation
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 2
push_to_hub: true
remove_unused_columns: true
report_to:
- wandb
wandb_project: review_evaluation
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1