# Model arguments
# meta-llama/Llama-3.1-8B
# model_name_or_path: Uni-SMART/SciLitLLM
# model_name_or_path: meta-llama/Llama-3.1-8B
# model_name_or_path: WestlakeNLP/DeepReviewer-7B
model_name_or_path:  WestlakeNLP/DeepReviewer-7B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

################ ASPECT #################
aspect: all

# Data training arguments
dataset_mixer:
  boda/review_evaluation_automatic_labels: 1.0
dataset_splits:
- train
- test
dataset_configs:
- all
preprocessing_num_workers: 24

prompt_type: instruction
generation_type: score_rationale
task: train

### Do we only train on completion? 
train_on_completion_only: true
packing: false


### PUSH TO HUB ###
push_to_hub: false
model_name: review_evaluation
dataset_name: review_evaluation_automatic_labels


# LoRA arguments
load_in_4bit: false
# use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# SFT trainer config
bf16: true
dataset_kwargs:
  add_special_tokens: true  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: true # No need to add <eos> across samples

do_eval: false
eval_strategy: epoch
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
hub_model_id: boda/review_evaluation_all
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 5
overwrite_output_dir: true
## Auto find batch size
auto_find_batch_size: false
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
remove_unused_columns: true
report_to:
- wandb
wandb_project: review_evaluation
save_strategy: "epoch"
save_steps: 100
save_total_limit: 3
seed: 42
warmup_ratio: 0.1

